AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mm-list-channels

  Sample SAM Template for mm-list-channels

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MmListChannelsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        MmListChannels:
          Type: Schedule
          Properties:
            Schedule: 'rate(20 days)'
            Enabled: False
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: MmListChannels
          MM_BASE_URL: ''
          MM_TEAM_ID: ''
          MM_POST_CHANNEL_ID: ''
          MM_TOKEN: ''
  MmListChannelsFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MmListChannelsFunction}
      RetentionInDays: 60

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MmListChannelsFunction:
    Value: !GetAtt MmListChannelsFunction.Arn
  # MmListChannelsFunctionIamRole:
  #   Value: !GetAtt MmListChannelsFunctionIamRole.Arn
